apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nadaomri12/argocd.git
    targetRevision: dev
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  # Définir les sous-applications ici
  sources:
    - repoURL: https://github.com/nadaomri12/argocd.git
      path: kubernetes/db
      targetRevision: dev
      helm:
        valueFiles:
          - ../values/db-values.yaml
    - repoURL: https://github.com/nadaomri12/argocd.git
      path: kubernetes/coaudit-helm
      targetRevision: dev
      helm:
        valueFiles:
          - ../values/frontend-values.yaml
    - repoURL: https://github.com/nadaomri12/argocd.git
      path: kubernetes/coaudit-helm
      targetRevision: dev
      helm:
        valueFiles:
          - ../values/backend-values.yaml
